apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: mayssaa   
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb
        image: mayssaayachi02052000/challengeoneimage:latest  
        ports:
        - containerPort: 5000 
        resources:
          requests:
            memory: "100Mi"  
            cpu: "100m"       
          limits:
            memory: "200Mi"  
            cpu: "200m"       
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: mayssaa  
spec:
  selector:
    app: webnodb
  ports:
    - protocol: TCP
      port: 80                
      targetPort: 5000        
  type: ClusterIP             