version: '3'
services:
  flaskapp:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - CONN_STR=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - my_network

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
