apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
        - name: webdb
          image: mayssaayachi02052000/webdb:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
spec:
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
