apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: mayssaa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
        - name: webdb
          image: mayssaayachi02052000/flaskdb:latest
          ports:
            - containerPort: 5000
          env:
            - name: CONN_STR
              value: "mongodb://mongodb-service.mayssaa.svc.cluster.local:27017"
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
spec:
  selector:
    app: webdb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort


